import { useState } from 'react';
import { Check, ChevronRight, CircleHelp, KeyRound, LockKeyhole, Save, SlidersHorizontal, ToggleLeft, ToggleRight } from 'lucide-react';

const initialProviders = [
  { name: 'ZHI / core', description: 'General reasoning and baseline comparisons', latency: '420 ms', enabled: true, color: '#6caeb0' },
  { name: 'ZHI / reasoning', description: 'Long-chain inference for dense arguments', latency: '680 ms', enabled: true, color: '#c4e538' },
  { name: 'ZHI / style', description: 'Voice, register, and structural rhythm', latency: '510 ms', enabled: true, color: '#ef7655' },
  { name: 'ZHI / concise', description: 'Compression without loss of meaning', latency: '290 ms', enabled: false, color: '#a8a195' },
  { name: 'ZHI / critic', description: 'Adversarial reading and blind spots', latency: '735 ms', enabled: false, color: '#a8a195' },
  { name: 'ZHI / synthesis', description: 'Cross-model consensus and final signal', latency: '910 ms', enabled: true, color: '#6caeb0' },
];

export default function Settings() {
  const [providers, setProviders] = useState(initialProviders);
  const [saved, setSaved] = useState(false);
  const [precision, setPrecision] = useState('balanced');
  const [traces, setTraces] = useState(true);
  const toggleProvider = (name: string) => setProviders((current) => current.map((provider) => provider.name === name ? { ...provider, enabled: !provider.enabled } : provider));
  const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 2400); };

  return <div className="instrument-grid min-h-[calc(100dvh-76px)] px-5 py-7 md:px-9 md:py-9"><div className="mx-auto max-w-[1060px]">
    <div className="animate-rise-in mb-9"><div className="mb-2 font-mono text-[10px] uppercase tracking-[.2em] text-[#4f9698]">Control room / preferences</div><h1 className="text-3xl font-semibold tracking-[-.04em] md:text-[40px]">Settings</h1><p className="mt-3 max-w-lg text-[13px] leading-relaxed text-muted-foreground">Tune the instrument for the way you read, write, and evaluate.</p></div>
    <div className="grid gap-7 lg:grid-cols-[185px_minmax(0,1fr)]">
      <nav className="flex gap-1 overflow-auto lg:block"><a href="#providers" className="focus-ring flex shrink-0 items-center gap-2 rounded-md bg-primary px-3 py-2.5 text-[11px] font-semibold text-primary-foreground" data-testid="link-settings-providers"><SlidersHorizontal size={14} /> Providers</a><a href="#account" className="focus-ring flex shrink-0 items-center gap-2 rounded-md px-3 py-2.5 text-[11px] font-medium text-muted-foreground hover:bg-muted hover:text-foreground" data-testid="link-settings-account"><KeyRound size={14} /> Account</a><a href="#privacy" className="focus-ring flex shrink-0 items-center gap-2 rounded-md px-3 py-2.5 text-[11px] font-medium text-muted-foreground hover:bg-muted hover:text-foreground" data-testid="link-settings-privacy"><LockKeyhole size={14} /> Privacy</a></nav>
      <div className="space-y-7">
        <section id="providers" className="animate-rise-in delay-1 rounded-xl border border-border bg-card" data-testid="section-provider-settings"><div className="border-b border-border p-5 md:p-6"><div className="flex items-start justify-between gap-3"><div><div className="font-mono text-[9px] uppercase tracking-[.18em] text-muted-foreground">Model mesh / 06 nodes</div><h2 className="mt-1 text-[16px] font-semibold">Provider preferences</h2><p className="mt-2 text-[11px] leading-relaxed text-muted-foreground">Active providers participate in evaluations and contribute to your intelligence score.</p></div><div className="hidden rounded-md bg-[#6caeb0]/12 px-2.5 py-2 font-mono text-[9px] uppercase tracking-[.1em] text-[#4f9698] sm:block">{providers.filter((provider) => provider.enabled).length} active</div></div></div><div className="divide-y divide-border">{providers.map((provider) => <div key={provider.name} className="flex items-center gap-3 p-5 md:px-6" data-testid={`row-provider-${provider.name.replaceAll(' ', '-').replace('/', '')}`}><span className="size-2 rounded-full" style={{ backgroundColor: provider.enabled ? provider.color : '#a8a195' }} /><div className="min-w-0 flex-1"><div className="text-[12px] font-semibold">{provider.name}</div><div className="mt-1 truncate text-[11px] text-muted-foreground">{provider.description}</div></div><span className="hidden font-mono text-[9px] text-muted-foreground sm:block">{provider.enabled ? provider.latency : 'disabled'}</span><button onClick={() => toggleProvider(provider.name)} className={`focus-ring flex items-center gap-1.5 rounded-md px-2 py-1.5 text-[10px] font-medium ${provider.enabled ? 'text-[#4f9698]' : 'text-muted-foreground'}`} data-testid={`button-toggle-${provider.name.replaceAll(' ', '-').replace('/', '')}`} aria-label={`${provider.enabled ? 'Disable' : 'Enable'} ${provider.name}`}>{provider.enabled ? <ToggleRight size={22} /> : <ToggleLeft size={22} />}<span className="hidden w-12 text-left sm:inline">{provider.enabled ? 'Enabled' : 'Off'}</span></button></div>)}</div></section>
        <section id="account" className="animate-rise-in delay-2 rounded-xl border border-border bg-card p-5 md:p-6" data-testid="section-account-settings"><div className="mb-5"><div className="font-mono text-[9px] uppercase tracking-[.18em] text-muted-foreground">Workspace behavior</div><h2 className="mt-1 text-[16px] font-semibold">Evaluation defaults</h2></div><div className="space-y-5"><div className="flex flex-col justify-between gap-3 border-b border-border pb-5 sm:flex-row sm:items-center"><div><div className="text-[12px] font-medium">Evaluation precision</div><div className="mt-1 text-[11px] text-muted-foreground">Trade response speed for a wider model consensus.</div></div><div className="flex rounded-md border border-border bg-muted/40 p-1">{['fast', 'balanced', 'thorough'].map((item) => <button key={item} onClick={() => setPrecision(item)} className={`focus-ring rounded px-2.5 py-1.5 font-mono text-[9px] uppercase tracking-[.08em] ${precision === item ? 'bg-card text-foreground shadow-sm' : 'text-muted-foreground'}`} data-testid={`button-precision-${item}`}>{item}</button>)}</div></div><div className="flex items-center justify-between gap-4"><div><div className="text-[12px] font-medium">Include raw model traces</div><div className="mt-1 text-[11px] text-muted-foreground">Expose intermediate evidence in analysis results.</div></div><button onClick={() => setTraces((value) => !value)} className={`focus-ring flex items-center gap-1.5 text-[10px] font-medium ${traces ? 'text-[#4f9698]' : 'text-muted-foreground'}`} data-testid="button-toggle-traces">{traces ? <ToggleRight size={22} /> : <ToggleLeft size={22} />}<span>{traces ? 'Enabled' : 'Off'}</span></button></div></div></section>
        <section id="privacy" className="animate-rise-in delay-3 flex flex-col items-start justify-between gap-4 rounded-xl border border-[#6caeb0]/35 bg-[#6caeb0]/[.07] p-5 sm:flex-row sm:items-center md:p-6" data-testid="section-save-settings"><div className="flex gap-3"><CircleHelp size={17} className="mt-0.5 shrink-0 text-[#4f9698]" /><div><div className="text-[12px] font-semibold">Changes stay in this workspace</div><div className="mt-1 text-[11px] leading-relaxed text-muted-foreground">Provider preferences are applied to your next execution. No document content is changed.</div></div></div><button onClick={save} className="focus-ring flex shrink-0 items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-[11px] font-semibold text-primary-foreground" data-testid="button-save-settings">{saved ? <Check size={14} /> : <Save size={14} />}{saved ? 'Saved' : 'Save preferences'}</button></section>
      </div>
    </div>
  </div></div>;
}